[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.7", features = ["blocking"] }
regex = { regex = "1.5.4" }

[[bin]]
name = "day_1"
path = "day_1.rs"

[[bin]]
name = "day_2"
path = "day_2.rs"

[[bin]]
name = "day_3"
path = "day_3.rs"
